### ISSUE TITLE
Publish SOPS decrypt GitHub action in Metro Digital org

### ISSUE THREAD

**Issue by pavishenoy-metro** [metro-digital/sops-decrypt#3]
**Goal** 

Publish SOPS decrypt GitHub action in Metro digital org as Metro digital org is the right place for all open source projects.

**Tasks**

1.  Open source SOPS decrypt github action.
2.  Adapt WaaS workflow generator to use the new SOPS  Github action repository.

**Comment by navyatejaotturu-metronom** [comment]
Before open sourcing this action we need to add relevant content in `CONTRIBUTING.md`. 

Also, we should introduce tags as we did for [`setup-tools-for-waas`](https://github.com/metro-digital/setup-tools-for-waas) action as shown below.

- Tag `v0.x`, can be used while using the action to use latest minor version of the action all the time. e.g., `v0.1.10`, `v0.10.1`

- Tag `v0.1`, can be used while using the action to use latest patch version of the action all the time. e.g,. `v0.1.1`,` v0.1.10`

**Comment by siilarsi** [comment]
We need to consider which license we would like to use for this repository. In our previously ["open-sourced" repository](https://github.com/metro-digital/setup-tools-for-waas) we used the MIT license, for practical purposes I would suggest that we go with that in this repository as well.

**Comment by pavishenoy-metro** [comment]
@mariuskiessling  has documented to use Apache license in this document https://confluence.metrosystems.net/x/E5DcFw

Carsten did ask if we could use MIT license here: https://teams.microsoft.com/l/message/19:6b5e50a6a38744bc8caffd8619601c25@thread.tacv2/1614678217432?tenantId=64322308-09a9-47a3-8c1c-b82871d60568&groupId=0eecd2f9-c613-4e41-87ff-efff42e283b6&parentMessageId=1614350507309&teamName=GitHub%20Migration&channelName=General&createdTime=1614678217432

**Comment by uwehdaub** [comment]
Marius has already alligned with legal, that the MIT license can be used (at least for actions).
Maybe he forgot to document it.
We should definitely talk to him, before we add all these ugly license headers, which are requested by the Apache license.

**Comment by uwehdaub** [comment]
We also have to keep in mind, that not all users of this action will adapt at the same time.
So we have to make sure, that workflows expecting the action in the old location still work.

**Comment by mariuskiessling** [comment]
Apache License, Version 2.0 should be used in all projects. There are however a few exceptions in which it is acceptable to e.g. stick with the MIT license:
- Your project is bootstrapped from a template that was licensed under the MIT license (which was the case for your other workflow)
- You manage a fork of a project that was previously licensed under a non-Apache license.

Continuing using the existing license (e.g. MIT) will mean much less work for both you as well as the committee as we would not have to deal with any re-licensing or dual-licensing models. The reason 'the project is a workflow' would not be a valid reason for choosing the MIT license.
