### ISSUE TITLE
Support age encryption

### ISSUE THREAD

**Issue by luisgj** [metro-digital/sops-decrypt#387]
We can add support for age. That will be better than pgp as we will not have to base64 encode huge keys.

https://github.com/getsops/sops?tab=readme-ov-file#encrypting-using-age

**Comment by uwehdaub** [comment]
Hi @luisgj 

thanks for your suggestion.
We implemented this action as a supporting action to be used in [WaaS](https://github.com/metro-digital-inner-source/waas) and [Secret Manager](https://github.com/metro-digital-inner-source/secrets-manager).

Both are working with keys stored in the users GitHub account.
And GitHub currently only supports GPG for encryption.
So there is currently no need to support additional encryption methods in this action.

BR Uwe Daub
